### ISSUE TITLE
Configuring a Setup.hs script without cabal-doctest installed

### ISSUE THREAD

**Issue by RyanGlScott** [phadej/cabal-doctest#11]
This isn't an issue when using `cabal-doctest` so much as it is an issue when _not_ using `cabal-doctest`. Or, to put it it more clearly, we have several backwards-compatible `Setup` scripts which guard against the presence of `cabal-doctest` like so:

```haskell
#if MIN_VERSION_cabal_doctest(1,0,0)
-- This should be the code you use with Cabal-1.24 or later
import Distribution.Extra.Doctest ( defaultMainWithDoctests )
#else
-- Backported cabal-doctest code
-- In theory, this code should only ever be reachable with old versions of Cabal
#endif

main :: IO ()
main = defaultMainWithDoctests "doctests"
```

As I put in the comments above, there's a bit of an assumption that when you have a recent version of `Cabal` installed, you always go down one code path, and when you have an older `Cabal`, you go down the other, legacy code path. When _installing_ a package that uses this sort of script, this assumption should always hold, since your build tool will make sure you've installed `cabal-doctest` if you require it (i.e., if you're using a recent `Cabal`).

But https://github.com/ekmett/lens/issues/721 revealed that this assumption doesn't always hold when you simply _configure_ a package. Here's a simple way to illustrate the problem:

```
$ /opt/cabal/2.0/bin/cabal get distributive
Unpacking to distributive-0.5.2/
$ cd distributive-0.5.2/
$ /opt/cabal/2.0/bin/cabal sandbox init
$ /opt/cabal/2.0/bin/cabal configure -w /opt/ghc/8.2.1/bin/ghc
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: distributive-0.5.2:+tagged
unknown package: tagged (dependency of distributive-0.5.2:+tagged)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: distributive, distributive-0.5.2:flag,
taggedTrying configure anyway.
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )

dist/setup/setup.hs:103:7: error:
    • Couldn't match expected type ‘IO ()’
                  with actual type ‘String -> IO ()’
    • In a stmt of a 'do' block:
        rewriteFile (testAutogenDir </> "Build_doctests.hs")
          $ unlines
              ["module Build_doctests where", "", "pkgs :: [String]",
               "pkgs = " ++ (show $ formatDeps $ testDeps libcfg suitecfg), ....]
      In the second argument of ‘($)’, namely
        ‘do let testAutogenDir = autogenComponentModulesDir lbi suitecfg
            createDirectoryIfMissingVerbose verbosity True testAutogenDir
            rewriteFile (testAutogenDir </> "Build_doctests.hs")
              $ unlines ["module Build_doctests where", "", ....]’
      In the expression:
        when (testName suite == fromString testsuiteName)
          $ do let testAutogenDir = autogenComponentModulesDir lbi suitecfg
               createDirectoryIfMissingVerbose verbosity True testAutogenDir
               rewriteFile (testAutogenDir </> "Build_doctests.hs")
                 $ unlines ["module Build_doctests where", "", ....]
    |
103 |       rewriteFile (testAutogenDir </> "Build_doctests.hs") $ unlines
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

dist/setup/setup.hs:103:20: error:
    • Couldn't match type ‘[Char]’
                     with ‘Distribution.Verbosity.Verbosity’
      Expected type: Distribution.Verbosity.Verbosity
        Actual type: FilePath
    • In the first argument of ‘rewriteFile’, namely
        ‘(testAutogenDir </> "Build_doctests.hs")’
      In the expression:
        rewriteFile (testAutogenDir </> "Build_doctests.hs")
      In a stmt of a 'do' block:
        rewriteFile (testAutogenDir </> "Build_doctests.hs")
          $ unlines
              ["module Build_doctests where", "", "pkgs :: [String]",
               "pkgs = " ++ (show $ formatDeps $ testDeps libcfg suitecfg), ....]
    |
103 |       rewriteFile (testAutogenDir </> "Build_doctests.hs") $ unlines
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

dist/setup/setup.hs:168:18: error:
    • Couldn't match type ‘Distribution.Types.MungedPackageId.MungedPackageId’
                     with ‘Distribution.Types.PackageId.PackageIdentifier’
      Expected type: [(UnitId, PackageId)]
        Actual type: [(UnitId,
                       Distribution.Types.MungedPackageId.MungedPackageId)]
    • In the expression:
        nub $ componentPackageDeps xs ++ componentPackageDeps ys
      In an equation for ‘testDeps’:
          testDeps xs ys
            = nub $ componentPackageDeps xs ++ componentPackageDeps ys
    |
168 | testDeps xs ys = nub $ componentPackageDeps xs ++ componentPackageDeps ys
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Ack! Things went wrong here because we have a recent `Cabal` installed, but since we were in a fresh sandbox, we also didn't have `cabal-doctest` installed. Therefore we went down the wrong (legacy) codepath, and unsurprisingly, the more recent `Cabal` API doesn't work against the legacy code.

My question is: is there anything we can do here to lessen the surprise for users who might run into this situation? Obviously, we can't keep updating the legacy code in these `Setup` scripts forever to support new versions of `Cabal`—after all, we created `cabal-doctest` in the first place to avoid having to do that! Perhaps we should emit a large, scary GHC warning whenever you go down the legacy codepath with a recent `Cabal`? Or is there a more graceful way to handle this?

**Comment by phadej** [comment]
First of all, I think that "Trying configure anyway." is a bug in `cabal`.
Secondly: I opened an issue in `Cabal` not to break `rewriteFile`

But at last, would it be ok to just disable `doctests` if run configured thru the legacy codepath, to reduce the used API surface; though for that one needs `rewriteFile`. AFAIK we cannot disable components in custom setup, so we'd need to `rewriteFile` configuration so that `doctests` just don't do anything.

**Comment by RyanGlScott** [comment]
> Secondly: I opened an issue in Cabal not to break `rewriteFile`

That's good, but more importantly, this could happen with _any_ `Cabal` API change, and given the library's rapid development, I think it's inevitable that this scenario will happen again at some point, even if this particular issue is fixed.

> First of all, I think that "Trying configure anyway." is a bug in `cabal`.

Now that would be an ideal solution, I think. After all, `custom-setup` dependencies are dependencies like any other, so trying to run the `Setup` code without its dependencies seems pretty skeevy to me. (Is there an open issue for this, BTW?)

Alas, this isn't implemented (yet?), so we'll need to think of some other way to approach the problem for current `Cabal`s.

**Comment by phadej** [comment]
I opened an issue in `cabal` and will fix it ASAP (if there aren't any objections; yet only after May Day).

About second point, I think supporting old `cabal-install`s is more or less wasted work. As newest 
`cabal-installs` support compiling with quite old GHCs, I don't see a valid reason to keep supporting them. Recent enough `cabal-install` set `MIN_VERSION_` macros, so this issue can be fixed in 
in shims. Yet I'd like to keep shims small so we don't need to fix them. It's very unfortunate `rewriteFile` BC slipped in, hopefully it can be reverted before `Cabal-2.0` is released, otherwise we have to re-upload all the packages.

I.e. my proposal is to have

```haskell
#ifndef MIN_VERSION_base
-- imports
main = defaultMain -- doctest compiling will fail; but the package will build ok.
#else
-- imports
main = defaultMainWithDoctests
```
```

**Comment by phadej** [comment]
`Cabal-2.0` support can be resurrected with a similar change as in 
```
https://github.com/phadej/cabal-doctest/commit/b01ae011aa4456fd29110262c238cef19ad987bd
```

---

It's unfortunate the breaking change into Cabal-2.0 API slipped very late in the release-cycle. I'm not sure if it's worth to update the shim parts of `Setup.hs` files. It's up to you @RyanGlScott

**Comment by RyanGlScott** [comment]
I doubt I'll bother with releasing a new Hackage version of every single library which uses `cabal-doctest`, but I think it'd be worth it for me to at least update the shims in the HEAD versions of each library, since that's where people would be most likely run into this `cabal configure` issue.

But before I do this, perhaps we should come to an agreement on how to deal with this issue going forward. Perhaps if you run `cabal configure` with a newish `Cabal` and you _don't_ have `cabal-doctest` installed (i.e., `MIN_VERSION_cabal_doctest` isn't defined), then we could emit a warning and default to using `defaultMain`, like so:

```haskell
module Warning
  {-# WARNING ["You are configuring this package without cabal-doctest installed.",
               "The doctests test-suite will not work as a result.",
               "To fix this, install cabal-doctest before configuring."] #-}
  () where
```
```haskell
{-# LANGUAGE CPP #-}
module Main where

#if MIN_VERSION_cabal_doctest(1,0,0)
main = defaultMainWithDoctests
#elif MIN_VERSION_Cabal(1,24,0)
import Warning ()

main = defaultMain
#else
-- Compatibility shim
#endif
```

That way, these shims won't break if someone runs `cabal configure` too early, but they'll at least be informative enough to point people in the right direction.

**Comment by phadej** [comment]
![image](https://cloud.githubusercontent.com/assets/51087/25783648/736093a0-3368-11e7-83df-aee4c027f51d.png)

**Comment by RyanGlScott** [comment]
I like it!

I take since you bothered to implement it and post a screenshot, that you approve of my suggestion? :)

**Comment by RyanGlScott** [comment]
OK, the consensus that we reached in https://github.com/ekmett/bound/pull/55 was to use the simplified `Setup.hs` script proposed in https://github.com/ekmett/bound/pull/56.

I have a PR (#15) which updates the example in this repo to use the simplified `Setup.hs` script, so once we endorse that, I'd say we can close this issue.
