### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by pepeiborra** [phadej/cabal-doctest#25]
We are prevented from using cabal-doctest because our test suite uses `NoImplicitPrelude`

**Comment by RyanGlScott** [comment]
I'll prepare a new release soon.

**Comment by RyanGlScott** [comment]
I've uploaded [`cabal-doctest-1.0.3`](http://hackage.haskell.org/package/cabal-doctest-1.0.3) to Hackage with this change.

**Comment by pepeiborra** [comment]
Thanks!
