### ISSUE TITLE
Build_doctests isn't generated unless Cabal file defines a library

### ISSUE THREAD

**Issue by peti** [phadej/cabal-doctest#27]
I tried for quite a while now to run a doctest suite with `cabal-doctest` in a package that defines an executable, but no library, and all attempts invariably failed because the required `Build_doctests.hs` file wasn't generated. Then I added an *empty* `Library` stanza to my Cabal file, and immediately everything worked! I'm not sure why things work that way, but it doesn't seem right. Is that a bug, maybe?

**Comment by phadej** [comment]
It's the way things work. `cabal-doctest` is designed for libraries in mind, e.g. it passes to`doctest` modules from `library` stanza.

So, unless there are very good reasons otherwise (as you can put your executable modules into library, and have dummy `main = defaultMain` `Main.hs`), I'll close this as wontfix.

**Comment by peti** [comment]
Hmm, well, I think it's somewhat unpleasant that I have to structure my code in a particular way to make `doctest-cabal` happy rather than the tool being happy with the way I structure my project, especially considering that having doctests in an exe-only project doesn't seem like a particularly outlandish use-case.

**Comment by phadej** [comment]
@peti, I see. You can check how `cabal-doctest` is done, it uses `withLibLBI` in https://github.com/phadej/cabal-doctest/blob/5746d4e03ee32b696cd7bcda669618ed2ba8b2a5/src/Distribution/Extra/Doctest.hs#L168

Then you'll need to write `withMainComponent`, which would be like `withLibLBI` if library exists, or an `Exe` if exactly one exists. Supporting multiple-components would be way to complicated for this *hack* to work.

**Comment by RyanGlScott** [comment]
I share the opinion that we should support the ability to run `doctest`s in executables. Moreover, executables aren't the only way you can come up with multiple components that have `doctest`s: in `Cabal-2.0` and later, you can also have [internal libraries](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-library-reexported-modules)! In fact, `withLibLBI` actually [runs once per library](https://hackage.haskell.org/package/Cabal-2.0.0.2/docs/Distribution-Simple-LocalBuildInfo.html#v:withLibLBI), _including internal libraries_, so I bet that today's `cabal-doctest` would break in the presence of internal libraries, which is quite unfortunate.

You seem to be under the impression that supporting multiple components wouldn't work, but I disagree! I think it would be quite feasible, provided that we clearly delineate which generated modules are for which components. At the moment, we only generate a single `Build_doctests` module, under the (naïve) belief that only the main library component will have `doctest`s. But we could just as well generate `Build_doctests_executable_name1`, `Build_doctests_internal_library_name1`, etc. for each component. From there, folks can customize their test suite drivers to run `doctest` on each `Build_doctests_*` modules' set of flags at a time.

What's more, if we adopt this strategy of one `Build_doctests_*` module per component, this change should be completely backwards compatible. So I say: let's just do it.

**Comment by phadej** [comment]
@RyanGlScott I don't disagree. If you or someone else is going to implement this, please go for single `Build_doctest` with a list of various configurations.

*However*

- I think this library is a **hack** and I want to have better solution by `cabal-install-2.4` (GHC-8.6).
    - and  I'd rather spend dev cycles into making proper `cabal new-doctest` (fwiw, I already considered multiple components there!), and slowly we are progressing towards (you don't believe, but parser work helps with that!)
- And as a consequence, I don't want to encourage using this library if there aren't very good reason, like you are writing library `stack`, `cabal sandbox` and `cabal new-build` users are working with.
    - Already now it makes `new-build` abandon per-component build, because of `build-type: Custom`. `new-build` could be much faster! cross-compilation would be simpler, etc.

There is an alternative to this library already today: `.ghc.environment` files. I really have to write a proper blog post about that, as the issue rises often enough (it's great people are using doctest more and more!). Drawbacks are that it works only with GHC-8.0+, and `cabal new-install` isn't yet in HVR's PPA's `cabal-install-head` (so I use an auxiliary python script). But in short, if you have `doctest` executable and `.ghc.environment` file, things *just work*. See 
https://github.com/phadej/tree-diff/pull/9

**Comment by RyanGlScott** [comment]
I complete agree that `cabal-doctest` is quite hacky—all I'm saying is that adding this particular feature is straightforward. Straightforward enough, in fact, that I've done so in #28.

**Comment by peti** [comment]
> In short, if you have doctest executable and .ghc.environment file, things just work.

I tried to run doctest-0.13.0 in a `cabal new-build` environment with a `.ghc.environment.x86_64-linux-8.0.2` file present, but that did not work for me:

~~~
$ doctest src/

src/Main.hs:5:1: error:
    Failed to load interface for ‘Paths_mcp’
    Perhaps you meant
      Paths_amqp
      Paths_amqp
    Use -v to see a list of the files searched for.
~~~

Am I missing something terribly obvious?

**Comment by phadej** [comment]
Ah, for `Paths_pkg` you really need to know where `cabal` will put `Paths_pkg.hs`. The place is deterministic.

However, `cabal-doctest-1.0.4` with components support is released.
