### ISSUE TITLE
Failure with GHC 8.8 / Cabal 2.5

### ISSUE THREAD

**Issue by deepfire** [phadej/cabal-doctest#42]
This is with Cabal 2.5 / GHC 8.8:
```
[1 of 1] Compiling Distribution.Extra.Doctest ( src/Distribution/Extra/Doctest.hs, dist/build/D

src/Distribution/Extra/Doctest.hs:437:60: error:
    ���<80>��� Couldn't match type ���<80><98>Distribution.Types.LibraryName.LibraryName���<80><99>
                     with ���<80><98>Maybe
                             Distribution.Types.UnqualComponentName.UnqualComponentName���<80>
      Expected type: Library
                     -> Maybe Distribution.Types.UnqualComponentName.UnqualComponentName
        Actual type: Library
                     -> Distribution.Types.LibraryName.LibraryName
    ���<80>��� In the second argument of ���<80><98>(.)���<80><99>, namely ���<80><98>libName���<80><99>
      In the second argument of ���<80><98>(.)���<80><99>, namely
        ���<80><98>fmap unUnqualComponentName . libName���<80><99>
      In the expression: NameLib . fmap unUnqualComponentName . libName
    |
437 |     mbLibraryName = NameLib . fmap unUnqualComponentName . libName
    |                                                            ^^^^^^^
```
(Sorry for the botched Unicode, tty copy-paste can sometimes do this..)

**Comment by RyanGlScott** [comment]
This is expected—`Cabal-2.5` made a breaking change that affects `cabal-doctest`. Given that `Cabal` has a relatively volatile API that changes frequently leading up to new GHC releases, I don't think it's necessarily a good idea to try and have `cabal-doctest` chase that moving target.

In the meantime, there's a [patch in `head.hackage`](https://github.com/hvr/head.hackage/pull/91) which works around the issue. Does that work for you?

**Comment by deepfire** [comment]
@RyanGlScott, the patch helped, indeed!

**Comment by deepfire** [comment]
@RyanGlScott, except for its `Cabal` version bound, though, which is still `< 2.5` that breaks 8.8 : -)

**Comment by RyanGlScott** [comment]
Why not just use `--allow-newer`?

I'm not willing to relax the upper version bounds until the full GHC 8.8 release, as that invites the possibility that there will be a last-minute change in the 8.8 cycle that breaks existing uploads of `cabal-doctest` on Hackage. And no, this isn't me just being paranoid—[this has actually happened before](https://github.com/phadej/cabal-doctest/issues/12).

**Comment by phadej** [comment]
Nix can jailbreak packages, i.e. remove all bounds?

**Comment by phadej** [comment]
Also

```
% cabal v1-configure --help|grep allow
    --allow-older[=DEPS]                                 Ignore lower bounds in all
    --allow-newer[=DEPS]                                 Ignore upper bounds in all
```

**Comment by deepfire** [comment]
@phadej, 
> Nix can jailbreak packages, i.e. remove all bounds?
..yes, but not in conditional branches.
> cabal v1-configure...
Aha! That's what I missed from the online docs. Thank you!
