### ISSUE TITLE
cabal-doctest support for .hsc files?

### ISSUE THREAD

**Issue by RyanGlScott** [phadej/cabal-doctest#8]
I encountered an interesting problem recently: `cabal-doctest` doesn't seem to mix well with `hsc2hs`. In particular, if you have a library with any `.hsc` file (regardless of whether it actually contains any doctests), trying to run `doctest` on that library via `cabal-doctest` will always fail with an error like this:

```
$ cabal test
Preprocessing test suite 'doctests' for distributive-0.5.2...
Preprocessing library distributive-0.5.2...
Preprocessing test suite 'spec' for distributive-0.5.2...
Running 2 test suites...
Test suite doctests: RUNNING...

<no location info>: error:
    module ‘Data.Distributive’ is a package module
-i/home/rgscott/Documents/Hacking/Haskell/distributive-0.5.2/dist/build/autogen
-i/home/rgscott/Documents/Hacking/Haskell/distributive-0.5.2/src
-hide-all-packages
-package-db=dist/package.conf.inplace
-optP-include
-optPdist/build/autogen/cabal_macros.h
-package-id=base-4.9.1.0
-package-id=base-orphans-0.5.4-ABoxiBf7nXc7Qqh66CgYc9
-package-id=tagged-0.8.5-jDBtbBndklGIlXZjVMhpH
-package-id=transformers-0.5.2.0
-package-id=transformers-compat-0.5.1.4-84sV5mkFftgD9qwogvuEDr
-package-id=doctest-0.11.1-Iq0kyguMBZj6Gqp1YR6VOk
Data.Distributive
Data.Distributive.Generic
Test suite doctests: FAIL
Test suite logged to: dist/test/distributive-0.5.2-doctests.log
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/distributive-0.5.2-spec.log
1 of 2 test suites (1 of 2 test cases) passed.
```

(In that example, I just renamed `Data/Distributive.hs` to `Data/Distributive.hsc` from the `distributive` library for simplicity's sake.)

But it's a bit unfair to put the blame entirely on `cabal-doctest` here, as really the error comes from `doctest` itself. If you have any file with an `.hsc` extension, then directly invoking `doctest` on it also brings about the error:

```
$ touch Foo.hsc
$ doctest Foo

<no location info>: error: module ‘Foo’ is a package module
```

Perhaps this isn't too surprising when you think about it, since we need `hsc2hs` to preprocess the `.hsc` file before `doctest` can operate on the resulting `.hs` file. One might argue that it should be `doctest`'s job to call `hsc2hs` if it sees a `.hsc` file... but should `doctest` also have knowledge about `.chs` files (for `c2hs`) as well? What about other preprocessors? The more one thinks about it, the uglier it sounds to actually implement at the `doctest` level.

So my thought is: what if we trained `cabal-doctest` to do this? After all, `Cabal` knows about `hsc2hs`, `c2hs`, etc., so it is in a much better position to deal with this than `doctest` alone. Of course, actually implementing will assuredly be trickier than I think it will.

Alternatively, we could just wait until [`cabal doctest`](https://github.com/haskell/cabal/issues/2327) is a reality.

Either way, we should think of _some_ way to work around this, as not being able to use `hsc2hs` and `doctest` together is pretty annoying.

**Comment by phadej** [comment]
Do you have a (public) package where this is a problem.

Is it correct that GHC invokes `hsc2hs` for `hsc` files,  or is it `cabal` which knows how to preprocess them. What's about `.chs` and `.c2hs`?

If `cabal` does the preprocessing, than I hope this isn't hard (but not easy either) to fix in `cabal-doctest`.

**Comment by RyanGlScott** [comment]
I originally encountered this in `quine`, which had a `Setup.hs` shim for `doctests` and a `.hsc` file at the same time. It turned out that `quine` doesn't even use doctests at all internally, so I eventually decided to [just remove](https://github.com/ekmett/quine/pull/13) the custom `Setup.hs` script, but if `quine` _had_ been using `doctests`, we'd have been in trouble.

GHC has no knowledge of `hsc2hs` or `c2hs` whatsoever—it's `Cabal` that invokes those preprocessors on `.hsc` or `.chs` files before compiling them.

**Comment by phadej** [comment]
Ok, then maybe `Cabal` already does preprocessing, and I just have to find where the results are. I'll check next week. Today I'll try to not to do anything, especially fool myself :)

**Comment by peti** [comment]
I have run into the same issue. I wanted to use this library precisely because I was having trouble doctesting my hsc2hs-base code. It would be really great if you could add support for that use case.

**Comment by phadej** [comment]
@peti do you have a public repository, where I could test that `cabal-doctest` actually works with real world package?

**Comment by phadej** [comment]
@peti, are you using `stack`, could you test a branch in https://github.com/phadej/cabal-doctest/pull/14 if it works for you?

**Comment by peti** [comment]
@phadej, I created https://github.com/peti/hsyslog/tree/t/cabal-doctest-support in my `hsyslog` project to `hsc2hs` support. I run the build with `cabal-install`. I usually don't use `stack`.

**Comment by peti** [comment]
I tried #14 with `cabal-install` and it works fine!

**Comment by phadej** [comment]
@peti Great, I'll cut new release shortly.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cabal-doctest-1.0.2 on Hackage.

**Comment by peti** [comment]
Thank you very much for you efforts!
