### ISSUE TITLE
How to handle code involving unboxed tuples

### ISSUE THREAD

**Issue by RyanGlScott** [phadej/cabal-doctest#9]
When testing the [`structs`](https://github.com/ekmett/structs) library with `cabal-doctest`, I ran into this error:

```
Test suite doctests: RUNNING...
Error: bytecode compiler can't handle unboxed tuples.
  Possibly due to foreign import/export decls in source.
  Workaround: use -fobject-code, or compile this module to .o separately.
```

Or, if you want a more minimal example than `structs`, you can just use this simple file that uses `UnboxedTuples`:

```haskell
{-# LANGUAGE UnboxedTuples #-}
module Foo where

-- | A simple test involving tuples.
-- >>> foo
-- 3
foo :: Int
foo = let (# x, y #) = (# 1, 2 #) in x + y
```
```
$ doctest Foo.hs
Error: bytecode compiler can't handle unboxed tuples and sums.
  Possibly due to foreign import/export decls in source.
  Workaround: use -fobject-code, or compile this module to .o separately.
### Failure in Foo.hs:5: expression `foo'
expected: "3"
 but got: ""
          "\ESC[0m\ESC[;1m<interactive>:23:1: \ESC[0m\ESC[;1m\ESC[31merror:\ESC[0m\ESC[;1m Variable not in scope: foo\ESC[0m\ESC[0m"
          "\ESC[0m\ESC[0m\ESC[0m\ESC[0m"
Examples: 1  Tried: 1  Errors: 0  Failures: 1
```

A workaround is to pass `-fobject-code` to `doctest`, and indeed, I [applied this fix manually to `doctests.hs` in `structs`](https://github.com/ekmett/structs/commit/7708a2dc965896564c9b13b3f4c5ee38ada38fe8#diff-094b3b0bf5f517cee3185746527b3dc9) to work around the issue in that library. But this feels somewhat unsatisfactory, since now I have to deviate from the template which works for 99% of libraries.

My question is: is there a way `cabal-doctest` could detect the use of `UnboxedTuples` automatically and bring in `-fobject-code` when needed? Or, if this isn't a good idea, should we instead include a section in the `README` warning about the perils of `UnboxedTuples`?

**Comment by phadej** [comment]
If we specify `other-extensions: UnboxedTuples`, than `cabal-doctest` can detect that.

Alternatively, is there a reason not to use `-fobject-code` always?

**Comment by RyanGlScott** [comment]
> If we specify `other-extensions: UnboxedTuples`, than `cabal-doctest` can detect that.

Ah, interesting idea.

> Alternatively, is there a reason not to use `-fobject-code` always?

I don't think we'd want to do this, since we'd be significantly increasing the time it takes for `doctest` to process each file, since it now has to compile each one. And in the end, `doctest` would (IIRC) still run the tests themselves in interpreted mode, so I don't think you'd even get any performance benefits from using object code.

**Comment by phadej** [comment]
I see, slowing `doctest` is quite bad, they are slow to begin with.

I can take a look on `structs` tomorrow.

**Comment by ekmett** [comment]
I think we have to use -fobject-code in this case, as we can't construct 'foo' from ghci, no?

**Comment by ekmett** [comment]
This is how I've had to work around this in the past anyways. We're asking doctest to build in a very different manner to support a feature that isn't available to the bytecode compiler. It seems reasonable to have to ask.

**Comment by RyanGlScott** [comment]
> I think we have to use -fobject-code in this case, as we can't construct 'foo' from ghci, no?

Certainly. The question is: what is the best way to inform `cabal-doctest` that `-fobject-code` should be used in this specific instance? Currently, we have to hack it in to `doctests.hs` directly, but we're moving towards being able to specify `x-doctest-options: -fobject-code` in `structs.cabal` [soon](https://github.com/phadej/cabal-doctest/issues/10).
